"""phase 3 ingestion: media_files, asset technical columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 15:04:41.620077
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Migrations are additive (ADR-0006): no DROP or RENAME of anything a running
# release still reads, so an image rollback never needs a schema downgrade.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_sec", sa.Float(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_media_files_asset_id_assets"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_media_files_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_files_storage_key")),
    )
    op.create_index("ix_media_files_project", "media_files", ["project_id"], unique=False)
    op.create_index("uq_media_files_asset_kind", "media_files", ["asset_id", "kind"], unique=True)
    op.add_column("assets", sa.Column("video_codec", sa.Text(), nullable=True))
    op.add_column("assets", sa.Column("audio_codec", sa.Text(), nullable=True))
    op.add_column("assets", sa.Column("color_profile", sa.Text(), nullable=True))
    op.add_column("assets", sa.Column("has_audio", sa.Boolean(), nullable=True))
    op.add_column("assets", sa.Column("bit_depth", sa.SmallInteger(), nullable=True))
    op.add_column("assets", sa.Column("rotation", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "rotation")
    op.drop_column("assets", "bit_depth")
    op.drop_column("assets", "has_audio")
    op.drop_column("assets", "color_profile")
    op.drop_column("assets", "audio_codec")
    op.drop_column("assets", "video_codec")
    op.drop_index("uq_media_files_asset_kind", table_name="media_files")
    op.drop_index("ix_media_files_project", table_name="media_files")
    op.drop_table("media_files")
    # ### end Alembic commands ###
