"""EditPlan timeline schema, validation and versioning (spec §22-23)."""

from .models import (
    SCHEMA_VERSION,
    AudioClip,
    AudioSource,
    AudioTrack,
    CaptionTrack,
    Crop,
    Ducking,
    EditPlan,
    EffectRef,
    GraphicsItem,
    Keyframe,
    Sequence,
    Transform,
    Transition,
    VideoClip,
    VideoTrack,
)
from .registry import GRAPHICS_REGISTRY, ComponentSpec
from .validate import (
    AssetFacts,
    Issue,
    PlanValidationError,
    Severity,
    ValidationReport,
    ensure_valid,
    snap_to_frames,
    validate_plan,
)
from .versions import UPGRADERS, UnknownSchemaVersionError, load_plan

__all__ = [
    "GRAPHICS_REGISTRY",
    "SCHEMA_VERSION",
    "UPGRADERS",
    "AssetFacts",
    "AudioClip",
    "AudioSource",
    "AudioTrack",
    "CaptionTrack",
    "ComponentSpec",
    "Crop",
    "Ducking",
    "EditPlan",
    "EffectRef",
    "GraphicsItem",
    "Issue",
    "Keyframe",
    "PlanValidationError",
    "Sequence",
    "Severity",
    "Transform",
    "Transition",
    "UnknownSchemaVersionError",
    "ValidationReport",
    "VideoClip",
    "VideoTrack",
    "ensure_valid",
    "load_plan",
    "snap_to_frames",
    "validate_plan",
]
