/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: the process answers. No dependencies are touched.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: database, Redis and object storage all answer.
         */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Login
         * @description Exchange Mini App initData (validated server-side) for an access token.
         */
        post: operations["telegram_login_api_v1_auth_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Sliding session: a valid token buys a fresh one while the app is open.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** New Project */
        post: operations["new_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Project */
        patch: operations["patch_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive */
        post: operations["archive_api_v1_projects__project_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_v1_projects__project_id__assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Asset
         * @description One asset with its derived files (proxy, poster, filmstrip), shots and metadata.
         */
        get: operations["get_asset_api_v1_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/enhance-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Enhance Preview
         * @description Automatic grade (measured exposure / white balance + a creative profile)
         *     and voice cleanup with loudness for the platform, rendered on the proxy.
         */
        post: operations["request_enhance_preview_api_v1_assets__asset_id__enhance_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/caption-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Caption Preview
         * @description Render the asset with animated captions (Remotion layer composited by
         *     FFmpeg over the proxy). A request while one is running returns that one.
         */
        post: operations["request_caption_preview_api_v1_assets__asset_id__caption_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Asset Clips
         * @description Per-shot analysis (``clipanalysis/1``) with a sheet of three stills per shot.
         */
        get: operations["list_asset_clips_api_v1_assets__asset_id__clips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Project Clips
         * @description Every analysed shot of the project, in asset order — what the Director will choose from.
         */
        get: operations["list_project_clips_api_v1_projects__project_id__clips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Asset
         * @description Analyse the shots again (after an engine update).
         */
        post: operations["analyze_asset_api_v1_assets__asset_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transcript
         * @description Words with timings, segments, silences and subtitle cues (``transcript/1``).
         */
        get: operations["get_transcript_api_v1_assets__asset_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe Asset
         * @description Transcribe (again), optionally forcing a language when detection got it wrong.
         */
        post: operations["transcribe_asset_api_v1_assets__asset_id__transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_projects__project_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/reingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reingest Asset
         * @description Run ingestion again (after a media-engine update). Derived files are
         *     rewritten in place; the original is only read.
         */
        post: operations["reingest_asset_api_v1_assets__asset_id__reingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Upload
         * @description Open (or resume) a resumable multipart upload for one file.
         */
        post: operations["create_upload_api_v1_projects__project_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload
         * @description Upload state, including the parts storage already holds (for resume).
         */
        get: operations["get_upload_api_v1_uploads__session_id__get"];
        put?: never;
        post?: never;
        /** Abort Upload */
        delete: operations["abort_upload_api_v1_uploads__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Parts
         * @description Presigned PUT URLs for parts; each signature covers the part's Content-MD5.
         */
        post: operations["sign_parts_api_v1_uploads__session_id__parts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Progress */
        post: operations["report_progress_api_v1_uploads__session_id__progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Upload
         * @description Verify every part in storage, assemble the original and queue ingestion.
         */
        post: operations["complete_upload_api_v1_uploads__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Activity log. Default: the latest ``limit`` events, oldest first.
         */
        get: operations["list_events_api_v1_projects__project_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Server-Sent Events: replay after ``Last-Event-ID`` / ``after_id``, then live.
         */
        get: operations["stream_events_api_v1_projects__project_id__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisStatus
         * @enum {string}
         */
        AnalysisStatus: "queued" | "running" | "done" | "failed";
        /**
         * AnalysisSummary
         * @description State of an asset's shot analysis; the shots come from ``GET /assets/{id}/clips``.
         */
        AnalysisSummary: {
            status: components["schemas"]["AnalysisStatus"];
            /** Source */
            source: string | null;
            /** Clip Count */
            clip_count: number | null;
            /** Usable Avg */
            usable_avg: number | null;
            /** Error */
            error: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** ApiErrorBody */
        ApiErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown | null;
        };
        /** AssetDetail */
        AssetDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            kind: components["schemas"]["AssetKind"];
            status: components["schemas"]["AssetStatus"];
            /** Original Filename */
            original_filename: string;
            /** Extension */
            extension: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sort Index */
            sort_index: number;
            /** Etag */
            etag: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Fps */
            fps: number | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Uploaded At */
            uploaded_at: string | null;
            /** Ready At */
            ready_at: string | null;
            upload?: components["schemas"]["UploadStateOut"] | null;
            /** Video Codec */
            video_codec?: string | null;
            /** Audio Codec */
            audio_codec?: string | null;
            /** Color Profile */
            color_profile?: string | null;
            /** Color Label */
            color_label?: string | null;
            /** Has Audio */
            has_audio?: boolean | null;
            /** Bit Depth */
            bit_depth?: number | null;
            thumbnail?: components["schemas"]["SignedUrl"] | null;
            transcript_status?: components["schemas"]["TranscriptStatus"] | null;
            /** Transcript Language */
            transcript_language?: string | null;
            /** Transcript Finished At */
            transcript_finished_at?: string | null;
            analysis_status?: components["schemas"]["AnalysisStatus"] | null;
            /** Clip Count */
            clip_count?: number | null;
            /** Usable Avg */
            usable_avg?: number | null;
            media_info: components["schemas"]["MediaInfo"] | null;
            /** Files */
            files: components["schemas"]["MediaFileOut"][];
            /** Shots */
            shots: components["schemas"]["ShotOut"][];
            transcript?: components["schemas"]["TranscriptSummary"] | null;
            analysis?: components["schemas"]["AnalysisSummary"] | null;
            caption_preview?: components["schemas"]["CaptionPreviewOut"] | null;
            enhance_preview?: components["schemas"]["EnhancePreviewOut"] | null;
        };
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "video" | "audio" | "image" | "other";
        /** AssetList */
        AssetList: {
            /** Items */
            items: components["schemas"]["AssetOut"][];
        };
        /** AssetOut */
        AssetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            kind: components["schemas"]["AssetKind"];
            status: components["schemas"]["AssetStatus"];
            /** Original Filename */
            original_filename: string;
            /** Extension */
            extension: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sort Index */
            sort_index: number;
            /** Etag */
            etag: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Fps */
            fps: number | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Uploaded At */
            uploaded_at: string | null;
            /** Ready At */
            ready_at: string | null;
            upload?: components["schemas"]["UploadStateOut"] | null;
            /** Video Codec */
            video_codec?: string | null;
            /** Audio Codec */
            audio_codec?: string | null;
            /** Color Profile */
            color_profile?: string | null;
            /** Color Label */
            color_label?: string | null;
            /** Has Audio */
            has_audio?: boolean | null;
            /** Bit Depth */
            bit_depth?: number | null;
            thumbnail?: components["schemas"]["SignedUrl"] | null;
            transcript_status?: components["schemas"]["TranscriptStatus"] | null;
            /** Transcript Language */
            transcript_language?: string | null;
            /** Transcript Finished At */
            transcript_finished_at?: string | null;
            analysis_status?: components["schemas"]["AnalysisStatus"] | null;
            /** Clip Count */
            clip_count?: number | null;
            /** Usable Avg */
            usable_avg?: number | null;
        };
        /**
         * AssetStatus
         * @enum {string}
         */
        AssetStatus: "uploading" | "uploaded" | "ingesting" | "ready" | "failed" | "cancelled";
        /** AudioStream */
        AudioStream: {
            /** Codec */
            codec?: string | null;
            /** Profile */
            profile?: string | null;
            /** Channels */
            channels?: number | null;
            /** Channel Layout */
            channel_layout?: string | null;
            /** Sample Rate */
            sample_rate?: number | null;
            /** Bitrate */
            bitrate?: number | null;
            /** Bit Depth */
            bit_depth?: number | null;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * CaptionPreviewOut
         * @description The asset with animated captions burned in (Phase 7 motion engine).
         */
        CaptionPreviewOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /**
             * Style
             * @enum {string}
             */
            style: "dynamic" | "karaoke" | "minimal" | "bold";
            /**
             * Position
             * @enum {string}
             */
            position: "bottom" | "center" | "top";
            /** Error */
            error?: string | null;
            /** Updated At */
            updated_at?: string | null;
            video?: components["schemas"]["SignedUrl"] | null;
            download?: components["schemas"]["SignedUrl"] | null;
        };
        /** CaptionPreviewRequest */
        CaptionPreviewRequest: {
            /**
             * Style
             * @default dynamic
             * @enum {string}
             */
            style: "dynamic" | "karaoke" | "minimal" | "bold";
            /**
             * Position
             * @default bottom
             * @enum {string}
             */
            position: "bottom" | "center" | "top";
        };
        /** ClipList */
        ClipList: {
            /** Items */
            items: components["schemas"]["ClipOut"][];
        };
        /** ClipOut */
        ClipOut: {
            /**
             * Schema Version
             * @default clipanalysis/1
             * @constant
             */
            schema_version: "clipanalysis/1";
            /** Clip Id */
            clip_id: string;
            /** Index */
            index: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Duration */
            duration: number;
            /** Resolution */
            resolution: string | null;
            /** Fps */
            fps: number | null;
            /** Color Profile */
            color_profile: string | null;
            /**
             * Shot Type
             * @default unknown
             * @enum {string}
             */
            shot_type: "close_up" | "medium" | "wide" | "unknown";
            /** Subject */
            subject: string | null;
            /**
             * Face Detected
             * @default false
             */
            face_detected: boolean;
            /**
             * Face Count
             * @default 0
             */
            face_count: number;
            /** Faces */
            faces: components["schemas"]["Face"][];
            /** Person Position */
            person_position: ("left" | "center" | "right") | null;
            /**
             * Camera Motion
             * @default static
             * @enum {string}
             */
            camera_motion: "static" | "pan_left" | "pan_right" | "tilt_up" | "tilt_down" | "handheld" | "moving";
            /** Sharpness */
            sharpness: number;
            exposure: components["schemas"]["Exposure"];
            motion: components["schemas"]["Motion"];
            /** Camera Quality */
            camera_quality: number;
            /** Lighting Quality */
            lighting_quality: number;
            /**
             * Audio Present
             * @default false
             */
            audio_present: boolean;
            /**
             * Speech Present
             * @default false
             */
            speech_present: boolean;
            /**
             * Speech Ratio
             * @default 0
             */
            speech_ratio: number;
            /** Silence Segments */
            silence_segments: components["schemas"]["Span"][];
            /** Semantic Description */
            semantic_description: string | null;
            /** Usable Score */
            usable_score: number;
            /** Flags */
            flags: ("black" | "blurry" | "underexposed" | "overexposed" | "shaky" | "frozen" | "too_short" | "duplicate")[];
            /** Duplicate Of */
            duplicate_of: string | null;
            /** Best Frame */
            best_frame: number | null;
            /**
             * Source
             * @default metrics
             * @enum {string}
             */
            source: "metrics" | "metrics+vision";
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Asset Name */
            asset_name: string;
            sheet: components["schemas"]["SignedUrl"] | null;
        };
        /**
         * ColorInfo
         * @description Source color detection (spec §11 SOURCE DETECTION). Phase 8 builds the
         *     full transform chain on top of this; ingestion only needs to know enough
         *     to make a viewable proxy and to flag Log/HDR material.
         */
        ColorInfo: {
            /**
             * Profile
             * @enum {string}
             */
            profile: "rec709" | "rec2020_sdr" | "display_p3" | "hlg" | "pq" | "apple_log" | "log_suspected" | "srgb" | "unknown";
            /** Label */
            label: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /**
             * Hdr
             * @default false
             */
            hdr: boolean;
            /**
             * Log
             * @default false
             */
            log: boolean;
            /**
             * Dolby Vision
             * @default false
             */
            dolby_vision: boolean;
            /** Reasons */
            reasons?: string[];
        };
        /** ComponentCheck */
        ComponentCheck: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /**
         * EnhancePreviewOut
         * @description Automatic colour grade + voice cleanup and loudness on one clip (Phase 8).
         */
        EnhancePreviewOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /**
             * Profile
             * @enum {string}
             */
            profile: "neutral" | "cinematic_clean" | "warm_film" | "cool_teal" | "vivid_social" | "bw_classic";
            /** Intensity */
            intensity: number;
            /**
             * Target
             * @enum {string}
             */
            target: "social" | "youtube" | "podcast" | "broadcast";
            /** Error */
            error?: string | null;
            /** Updated At */
            updated_at?: string | null;
            video?: components["schemas"]["SignedUrl"] | null;
            download?: components["schemas"]["SignedUrl"] | null;
            before?: components["schemas"]["SignedUrl"] | null;
            after?: components["schemas"]["SignedUrl"] | null;
            /** Notes */
            notes?: string[];
            /** Lufs Before */
            lufs_before?: number | null;
            /** Lufs After */
            lufs_after?: number | null;
            /** Grade */
            grade?: {
                [key: string]: unknown;
            } | null;
        };
        /** EnhancePreviewRequest */
        EnhancePreviewRequest: {
            /**
             * Profile
             * @default cinematic_clean
             * @enum {string}
             */
            profile: "neutral" | "cinematic_clean" | "warm_film" | "cool_teal" | "vivid_social" | "bw_classic";
            /**
             * Intensity
             * @default 0.8
             */
            intensity: number;
            /**
             * Target
             * @default social
             * @enum {string}
             */
            target: "social" | "youtube" | "podcast" | "broadcast";
            /**
             * Denoise
             * @default auto
             * @enum {string}
             */
            denoise: "auto" | "off" | "light" | "medium" | "strong";
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /**
         * EventEnvelope
         * @description Wire format of an event, identical for the REST log and the SSE stream.
         */
        EventEnvelope: {
            /**
             * Id
             * @description Null for ephemeral events
             */
            id?: number | null;
            /** Project Id */
            project_id?: string | null;
            /** Type */
            type: string;
            /** @default info */
            level: components["schemas"]["EventLevel"];
            /** Source */
            source: string;
            /** Message */
            message: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Job Id */
            job_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EventLevel
         * @enum {string}
         */
        EventLevel: "debug" | "info" | "warning" | "error";
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventEnvelope"][];
            /** Next After Id */
            next_after_id: number | null;
        };
        /** Exposure */
        Exposure: {
            /** Mean */
            mean: number;
            /** Dark */
            dark: number;
            /** Bright */
            bright: number;
        };
        /** Face */
        Face: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Height */
            height: number;
            /** Score */
            score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Release */
            release: string;
        };
        /** JobList */
        JobList: {
            /** Items */
            items: components["schemas"]["JobOut"][];
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            queue: components["schemas"]["JobQueue"];
            /** Priority */
            priority: number;
            status: components["schemas"]["JobStatus"];
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Progress */
            progress: number | null;
            /** Progress Message */
            progress_message: string | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Run After
             * Format: date-time
             */
            run_after: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * JobQueue
         * @description Separate queues so heavy work never starves light work (spec §30-31).
         * @enum {string}
         */
        JobQueue: "io" | "cpu" | "gpu" | "render" | "llm";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "dead" | "cancelled";
        /** LimitsOut */
        LimitsOut: {
            /** Max Upload Bytes */
            max_upload_bytes: number;
            /** Storage Quota Bytes */
            storage_quota_bytes: number;
            /** Storage Used Bytes */
            storage_used_bytes: number;
            /**
             * Storage Reserved Bytes
             * @description Declared size of uploads still in progress
             */
            storage_reserved_bytes: number;
            /** Disk Free Bytes */
            disk_free_bytes: number | null;
            /** Part Size Bytes */
            part_size_bytes: number;
        };
        /** Loudness */
        Loudness: {
            /** Integrated Lufs */
            integrated_lufs?: number | null;
            /** Lra Lu */
            lra_lu?: number | null;
            /** True Peak Dbfs */
            true_peak_dbfs?: number | null;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            limits: components["schemas"]["LimitsOut"];
        };
        /** MediaFileOut */
        MediaFileOut: {
            /** Kind */
            kind: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            url: components["schemas"]["SignedUrl"];
        };
        /** MediaInfo */
        MediaInfo: {
            /**
             * Schema Version
             * @default mediainfo/1
             * @constant
             */
            schema_version: "mediainfo/1";
            /**
             * Kind
             * @enum {string}
             */
            kind: "video" | "audio" | "image" | "other";
            /** Container */
            container?: string | null;
            /** Duration */
            duration?: number | null;
            /** Size Bytes */
            size_bytes: number;
            /** Bitrate */
            bitrate?: number | null;
            video?: components["schemas"]["VideoStream"] | null;
            audio?: components["schemas"]["AudioStream"] | null;
            /**
             * Audio Streams
             * @default 0
             */
            audio_streams: number;
            color?: components["schemas"]["ColorInfo"] | null;
            /** Camera */
            camera?: {
                [key: string]: string;
            };
            /**
             * Has Location
             * @default false
             */
            has_location: boolean;
            loudness?: components["schemas"]["Loudness"] | null;
        };
        /** Motion */
        Motion: {
            /** Speed */
            speed: number;
            /** Shake */
            shake: number;
            /** Dx */
            dx: number;
            /** Dy */
            dy: number;
        };
        /** PartSignItem */
        PartSignItem: {
            /** Number */
            number: number;
            /**
             * Md5 B64
             * @description base64 of the part's 16-byte MD5
             */
            md5_b64: string;
        };
        /** PartSignRequest */
        PartSignRequest: {
            /** Parts */
            parts: components["schemas"]["PartSignItem"][];
        };
        /** PartSignResponse */
        PartSignResponse: {
            /** Parts */
            parts: components["schemas"]["SignedPart"][];
        };
        /** PresetOut */
        PresetOut: {
            id: components["schemas"]["ProjectPreset"];
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Aspect */
            aspect: string;
            /** Label */
            label: string;
            /** Family */
            family: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** @default reels_9x16 */
            preset: components["schemas"]["ProjectPreset"];
            /**
             * Fps
             * @default 30
             * @enum {integer}
             */
            fps: 24 | 25 | 30 | 50 | 60;
            /** Target Duration Sec */
            target_duration_sec?: number | null;
            /** @default auto */
            mode: components["schemas"]["ProjectMode"];
            /** @default auto */
            language: components["schemas"]["ProjectLanguage"];
            /** Brief */
            brief?: string | null;
        };
        /**
         * ProjectLanguage
         * @enum {string}
         */
        ProjectLanguage: "auto" | "uz" | "ru" | "en";
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["ProjectSummary"][];
        };
        /**
         * ProjectMode
         * @enum {string}
         */
        ProjectMode: "auto" | "assisted" | "manual";
        /** ProjectOut */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            preset: components["schemas"]["ProjectPreset"];
            /** Fps */
            fps: number;
            mode: components["schemas"]["ProjectMode"];
            status: components["schemas"]["ProjectStatus"];
            /** Asset Count */
            asset_count: number;
            /** Total Bytes */
            total_bytes: number;
            /** Progress */
            progress: number;
            active_stage: components["schemas"]["Stage"] | null;
            /** Active Stage Label */
            active_stage_label?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Target Duration Sec */
            target_duration_sec: number | null;
            language: components["schemas"]["ProjectLanguage"];
            /** Brief */
            brief: string | null;
            /** Stages */
            stages: components["schemas"]["StageOut"][];
            /** Cost Usd */
            cost_usd: number;
            /** Current Agent */
            current_agent: string | null;
        };
        /**
         * ProjectPreset
         * @enum {string}
         */
        ProjectPreset: "reels_9x16" | "youtube_16x9_1080" | "youtube_16x9_2160" | "square_1x1" | "portrait_4x5";
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "archived";
        /** ProjectSummary */
        ProjectSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            preset: components["schemas"]["ProjectPreset"];
            /** Fps */
            fps: number;
            mode: components["schemas"]["ProjectMode"];
            status: components["schemas"]["ProjectStatus"];
            /** Asset Count */
            asset_count: number;
            /** Total Bytes */
            total_bytes: number;
            /** Progress */
            progress: number;
            active_stage: components["schemas"]["Stage"] | null;
            /** Active Stage Label */
            active_stage_label?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            preset?: components["schemas"]["ProjectPreset"] | null;
            /** Fps */
            fps?: (24 | 25 | 30 | 50 | 60) | null;
            /** Target Duration Sec */
            target_duration_sec?: number | null;
            mode?: components["schemas"]["ProjectMode"] | null;
            language?: components["schemas"]["ProjectLanguage"] | null;
            /** Brief */
            brief?: string | null;
        };
        /** ReadyOut */
        ReadyOut: {
            /** Status */
            status: string;
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["ComponentCheck"];
            };
        };
        /**
         * Segment
         * @description Roughly a sentence (the engine's segmentation, split at long pauses).
         */
        Segment: {
            /** Id */
            id: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
            /** Words */
            words: components["schemas"]["Word"][];
            /** Avg Logprob */
            avg_logprob: number | null;
            /** No Speech Prob */
            no_speech_prob: number | null;
            /**
             * Question
             * @default false
             */
            question: boolean;
        };
        /** ShotOut */
        ShotOut: {
            /** Index */
            index: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Duration */
            duration: number;
        };
        /** SignedPart */
        SignedPart: {
            /** Number */
            number: number;
            /** Url */
            url: string;
            /**
             * Method
             * @default PUT
             */
            method: string;
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * SignedUrl
         * @description Short-lived presigned GET on the Mini App's own origin.
         */
        SignedUrl: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** Silence */
        Silence: {
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** Span */
        Span: {
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "upload" | "ingest" | "analysis" | "transcription" | "director" | "editor" | "color" | "audio" | "motion" | "captions" | "qa" | "render" | "delivery";
        /** StageOut */
        StageOut: {
            stage: components["schemas"]["Stage"];
            /** Label */
            label: string;
            status: components["schemas"]["StageStatus"];
            /** Progress */
            progress: number | null;
            /** Detail */
            detail: string | null;
            /**
             * Phase
             * @description Development phase in which this stage becomes operational
             */
            phase: number;
            /**
             * Available
             * @description False until the stage's phase has been built
             */
            available: boolean;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "pending" | "queued" | "running" | "done" | "failed" | "skipped" | "blocked" | "waiting_user";
        /**
         * SubtitleCue
         * @description Preset-neutral subtitle data: ≤ 2 lines. ``word_start``/``word_end``
         *     (exclusive) index ``Transcript.words``, so per-word timing stays available
         *     for animated captions without storing every word twice. The Caption agent
         *     (Phase 7) re-flows and styles these per output format.
         */
        SubtitleCue: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Lines */
            lines: string[];
            /** Word Start */
            word_start: number;
            /** Word End */
            word_end: number;
        };
        /** TelegramAuthRequest */
        TelegramAuthRequest: {
            /** Init Data */
            init_data: string;
        };
        /** TranscribeRequest */
        TranscribeRequest: {
            language?: components["schemas"]["ProjectLanguage"] | null;
        };
        /** Transcript */
        Transcript: {
            /**
             * Schema Version
             * @default transcript/1
             * @constant
             */
            schema_version: "transcript/1";
            /** Engine */
            engine: string;
            /** Language */
            language: string | null;
            /** Language Probability */
            language_probability: number | null;
            /**
             * Language Forced
             * @default false
             */
            language_forced: boolean;
            /** Duration */
            duration: number;
            /**
             * Speech Seconds
             * @default 0
             */
            speech_seconds: number;
            /**
             * Word Count
             * @default 0
             */
            word_count: number;
            /** Segments */
            segments: components["schemas"]["Segment"][];
            /** Silences */
            silences: components["schemas"]["Silence"][];
            /** Cues */
            cues: components["schemas"]["SubtitleCue"][];
        };
        /**
         * TranscriptStatus
         * @enum {string}
         */
        TranscriptStatus: "queued" | "running" | "done" | "failed";
        /**
         * TranscriptSummary
         * @description The state of an asset's transcription; the words themselves come from
         *     ``GET /assets/{id}/transcript``.
         */
        TranscriptSummary: {
            status: components["schemas"]["TranscriptStatus"];
            /** Requested Language */
            requested_language: string;
            /** Language */
            language: string | null;
            /** Language Probability */
            language_probability: number | null;
            /** Engine */
            engine: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Speech Sec */
            speech_sec: number | null;
            /** Word Count */
            word_count: number | null;
            /** Segment Count */
            segment_count: number | null;
            /** Engine Seconds */
            engine_seconds: number | null;
            /** Error */
            error: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Finished At */
            finished_at: string | null;
            subtitles_vtt?: components["schemas"]["SignedUrl"] | null;
            subtitles_srt?: components["schemas"]["SignedUrl"] | null;
        };
        /** UploadCreate */
        UploadCreate: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Content Type
             * @default application/octet-stream
             */
            content_type: string;
            /** Last Modified Ms */
            last_modified_ms?: number | null;
            /** Fingerprint */
            fingerprint: string;
        };
        /** UploadPartOut */
        UploadPartOut: {
            /** Number */
            number: number;
            /** Size */
            size: number;
            /** Etag */
            etag: string;
        };
        /** UploadProgressReport */
        UploadProgressReport: {
            /** Bytes Uploaded */
            bytes_uploaded: number;
            /**
             * Error
             * @description Last client-side failure (network, storage status)
             */
            error?: string | null;
        };
        /** UploadSessionOut */
        UploadSessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            status: components["schemas"]["UploadSessionStatus"];
            /** Size Bytes */
            size_bytes: number;
            /** Part Size */
            part_size: number;
            /** Part Count */
            part_count: number;
            /** Uploaded Parts */
            uploaded_parts: components["schemas"]["UploadPartOut"][];
            /** Bytes Uploaded */
            bytes_uploaded: number;
            /**
             * Resumed
             * @default false
             */
            resumed: boolean;
            asset: components["schemas"]["AssetOut"];
        };
        /**
         * UploadSessionStatus
         * @enum {string}
         */
        UploadSessionStatus: "active" | "completing" | "completed" | "aborted" | "expired" | "failed";
        /** UploadStateOut */
        UploadStateOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["UploadSessionStatus"];
            /** Bytes Reported */
            bytes_reported: number;
            /** Part Size */
            part_size: number;
            /** Part Count */
            part_count: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Telegram Id */
            telegram_id: number;
            /** Username */
            username: string | null;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Language Code */
            language_code: string | null;
            /** Photo Url */
            photo_url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoStream */
        VideoStream: {
            /** Codec */
            codec?: string | null;
            /** Profile */
            profile?: string | null;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Display Width */
            display_width: number;
            /** Display Height */
            display_height: number;
            /**
             * Rotation
             * @default 0
             */
            rotation: number;
            /** Fps */
            fps?: number | null;
            /**
             * Vfr
             * @default false
             */
            vfr: boolean;
            /** Pix Fmt */
            pix_fmt?: string | null;
            /** Bit Depth */
            bit_depth?: number | null;
            /** Chroma */
            chroma?: string | null;
            /** Bitrate */
            bitrate?: number | null;
            /** Frames */
            frames?: number | null;
            /** Color Range */
            color_range?: string | null;
            /** Color Primaries */
            color_primaries?: string | null;
            /** Color Transfer */
            color_transfer?: string | null;
            /** Color Space */
            color_space?: string | null;
        };
        /** Word */
        Word: {
            /** Word */
            word: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Probability */
            probability: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    telegram_login_api_v1_auth_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_presets_api_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    new_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_api_v1_projects__project_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_v1_projects__project_id__assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_enhance_preview_api_v1_assets__asset_id__enhance_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnhancePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhancePreviewOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_caption_preview_api_v1_assets__asset_id__caption_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptionPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptionPreviewOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_asset_clips_api_v1_assets__asset_id__clips_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_clips_api_v1_projects__project_id__clips_get: {
        parameters: {
            query?: {
                min_usable?: number | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_asset_api_v1_assets__asset_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_v1_assets__asset_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_asset_api_v1_assets__asset_id__transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_projects__project_id__jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reingest_asset_api_v1_assets__asset_id__reingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_api_v1_projects__project_id__uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_upload_api_v1_uploads__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_upload_api_v1_uploads__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_parts_api_v1_uploads__session_id__parts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartSignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartSignResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_progress_api_v1_uploads__session_id__progress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadProgressReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_api_v1_uploads__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_projects__project_id__events_get: {
        parameters: {
            query?: {
                before_id?: number | null;
                after_id?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_projects__project_id__events_stream_get: {
        parameters: {
            query?: {
                after_id?: number;
            };
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
