/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: the process answers. No dependencies are touched.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: database, Redis and object storage all answer.
         */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Login
         * @description Exchange Mini App initData (validated server-side) for an access token.
         */
        post: operations["telegram_login_api_v1_auth_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Sliding session: a valid token buys a fresh one while the app is open.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_v1_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** New Project */
        post: operations["new_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Project */
        patch: operations["patch_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive */
        post: operations["archive_api_v1_projects__project_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_v1_projects__project_id__assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Asset
         * @description One asset with its derived files (proxy, poster, filmstrip), shots and metadata.
         */
        get: operations["get_asset_api_v1_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_projects__project_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/reingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reingest Asset
         * @description Run ingestion again (after a media-engine update). Derived files are
         *     rewritten in place; the original is only read.
         */
        post: operations["reingest_asset_api_v1_assets__asset_id__reingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Upload
         * @description Open (or resume) a resumable multipart upload for one file.
         */
        post: operations["create_upload_api_v1_projects__project_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload
         * @description Upload state, including the parts storage already holds (for resume).
         */
        get: operations["get_upload_api_v1_uploads__session_id__get"];
        put?: never;
        post?: never;
        /** Abort Upload */
        delete: operations["abort_upload_api_v1_uploads__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign Parts
         * @description Presigned PUT URLs for parts; each signature covers the part's Content-MD5.
         */
        post: operations["sign_parts_api_v1_uploads__session_id__parts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Progress */
        post: operations["report_progress_api_v1_uploads__session_id__progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Upload
         * @description Verify every part in storage, assemble the original and queue ingestion.
         */
        post: operations["complete_upload_api_v1_uploads__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Activity log. Default: the latest ``limit`` events, oldest first.
         */
        get: operations["list_events_api_v1_projects__project_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Server-Sent Events: replay after ``Last-Event-ID`` / ``after_id``, then live.
         */
        get: operations["stream_events_api_v1_projects__project_id__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorBody */
        ApiErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown | null;
        };
        /** AssetDetail */
        AssetDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            kind: components["schemas"]["AssetKind"];
            status: components["schemas"]["AssetStatus"];
            /** Original Filename */
            original_filename: string;
            /** Extension */
            extension: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sort Index */
            sort_index: number;
            /** Etag */
            etag: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Fps */
            fps: number | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Uploaded At */
            uploaded_at: string | null;
            /** Ready At */
            ready_at: string | null;
            upload?: components["schemas"]["UploadStateOut"] | null;
            /** Video Codec */
            video_codec?: string | null;
            /** Audio Codec */
            audio_codec?: string | null;
            /** Color Profile */
            color_profile?: string | null;
            /** Color Label */
            color_label?: string | null;
            /** Has Audio */
            has_audio?: boolean | null;
            /** Bit Depth */
            bit_depth?: number | null;
            thumbnail?: components["schemas"]["SignedUrl"] | null;
            media_info: components["schemas"]["MediaInfo"] | null;
            /** Files */
            files: components["schemas"]["MediaFileOut"][];
            /** Shots */
            shots: components["schemas"]["ShotOut"][];
        };
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "video" | "audio" | "image" | "other";
        /** AssetList */
        AssetList: {
            /** Items */
            items: components["schemas"]["AssetOut"][];
        };
        /** AssetOut */
        AssetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            kind: components["schemas"]["AssetKind"];
            status: components["schemas"]["AssetStatus"];
            /** Original Filename */
            original_filename: string;
            /** Extension */
            extension: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sort Index */
            sort_index: number;
            /** Etag */
            etag: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Fps */
            fps: number | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Uploaded At */
            uploaded_at: string | null;
            /** Ready At */
            ready_at: string | null;
            upload?: components["schemas"]["UploadStateOut"] | null;
            /** Video Codec */
            video_codec?: string | null;
            /** Audio Codec */
            audio_codec?: string | null;
            /** Color Profile */
            color_profile?: string | null;
            /** Color Label */
            color_label?: string | null;
            /** Has Audio */
            has_audio?: boolean | null;
            /** Bit Depth */
            bit_depth?: number | null;
            thumbnail?: components["schemas"]["SignedUrl"] | null;
        };
        /**
         * AssetStatus
         * @enum {string}
         */
        AssetStatus: "uploading" | "uploaded" | "ingesting" | "ready" | "failed" | "cancelled";
        /** AudioStream */
        AudioStream: {
            /** Codec */
            codec?: string | null;
            /** Profile */
            profile?: string | null;
            /** Channels */
            channels?: number | null;
            /** Channel Layout */
            channel_layout?: string | null;
            /** Sample Rate */
            sample_rate?: number | null;
            /** Bitrate */
            bitrate?: number | null;
            /** Bit Depth */
            bit_depth?: number | null;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserOut"];
        };
        /**
         * ColorInfo
         * @description Source color detection (spec §11 SOURCE DETECTION). Phase 8 builds the
         *     full transform chain on top of this; ingestion only needs to know enough
         *     to make a viewable proxy and to flag Log/HDR material.
         */
        ColorInfo: {
            /**
             * Profile
             * @enum {string}
             */
            profile: "rec709" | "rec2020_sdr" | "display_p3" | "hlg" | "pq" | "apple_log" | "log_suspected" | "srgb" | "unknown";
            /** Label */
            label: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /**
             * Hdr
             * @default false
             */
            hdr: boolean;
            /**
             * Log
             * @default false
             */
            log: boolean;
            /**
             * Dolby Vision
             * @default false
             */
            dolby_vision: boolean;
            /** Reasons */
            reasons?: string[];
        };
        /** ComponentCheck */
        ComponentCheck: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /**
         * EventEnvelope
         * @description Wire format of an event, identical for the REST log and the SSE stream.
         */
        EventEnvelope: {
            /**
             * Id
             * @description Null for ephemeral events
             */
            id?: number | null;
            /** Project Id */
            project_id?: string | null;
            /** Type */
            type: string;
            /** @default info */
            level: components["schemas"]["EventLevel"];
            /** Source */
            source: string;
            /** Message */
            message: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Job Id */
            job_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EventLevel
         * @enum {string}
         */
        EventLevel: "debug" | "info" | "warning" | "error";
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventEnvelope"][];
            /** Next After Id */
            next_after_id: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Release */
            release: string;
        };
        /** JobList */
        JobList: {
            /** Items */
            items: components["schemas"]["JobOut"][];
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            queue: components["schemas"]["JobQueue"];
            /** Priority */
            priority: number;
            status: components["schemas"]["JobStatus"];
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Progress */
            progress: number | null;
            /** Progress Message */
            progress_message: string | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Run After
             * Format: date-time
             */
            run_after: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * JobQueue
         * @description Separate queues so heavy work never starves light work (spec §30-31).
         * @enum {string}
         */
        JobQueue: "io" | "cpu" | "gpu" | "render" | "llm";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "dead" | "cancelled";
        /** LimitsOut */
        LimitsOut: {
            /** Max Upload Bytes */
            max_upload_bytes: number;
            /** Storage Quota Bytes */
            storage_quota_bytes: number;
            /** Storage Used Bytes */
            storage_used_bytes: number;
            /**
             * Storage Reserved Bytes
             * @description Declared size of uploads still in progress
             */
            storage_reserved_bytes: number;
            /** Disk Free Bytes */
            disk_free_bytes: number | null;
            /** Part Size Bytes */
            part_size_bytes: number;
        };
        /** Loudness */
        Loudness: {
            /** Integrated Lufs */
            integrated_lufs?: number | null;
            /** Lra Lu */
            lra_lu?: number | null;
            /** True Peak Dbfs */
            true_peak_dbfs?: number | null;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            limits: components["schemas"]["LimitsOut"];
        };
        /** MediaFileOut */
        MediaFileOut: {
            /** Kind */
            kind: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            url: components["schemas"]["SignedUrl"];
        };
        /** MediaInfo */
        MediaInfo: {
            /**
             * Schema Version
             * @default mediainfo/1
             * @constant
             */
            schema_version: "mediainfo/1";
            /**
             * Kind
             * @enum {string}
             */
            kind: "video" | "audio" | "image" | "other";
            /** Container */
            container?: string | null;
            /** Duration */
            duration?: number | null;
            /** Size Bytes */
            size_bytes: number;
            /** Bitrate */
            bitrate?: number | null;
            video?: components["schemas"]["VideoStream"] | null;
            audio?: components["schemas"]["AudioStream"] | null;
            /**
             * Audio Streams
             * @default 0
             */
            audio_streams: number;
            color?: components["schemas"]["ColorInfo"] | null;
            /** Camera */
            camera?: {
                [key: string]: string;
            };
            /**
             * Has Location
             * @default false
             */
            has_location: boolean;
            loudness?: components["schemas"]["Loudness"] | null;
        };
        /** PartSignItem */
        PartSignItem: {
            /** Number */
            number: number;
            /**
             * Md5 B64
             * @description base64 of the part's 16-byte MD5
             */
            md5_b64: string;
        };
        /** PartSignRequest */
        PartSignRequest: {
            /** Parts */
            parts: components["schemas"]["PartSignItem"][];
        };
        /** PartSignResponse */
        PartSignResponse: {
            /** Parts */
            parts: components["schemas"]["SignedPart"][];
        };
        /** PresetOut */
        PresetOut: {
            id: components["schemas"]["ProjectPreset"];
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Aspect */
            aspect: string;
            /** Label */
            label: string;
            /** Family */
            family: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** @default reels_9x16 */
            preset: components["schemas"]["ProjectPreset"];
            /**
             * Fps
             * @default 30
             * @enum {integer}
             */
            fps: 24 | 25 | 30 | 50 | 60;
            /** Target Duration Sec */
            target_duration_sec?: number | null;
            /** @default auto */
            mode: components["schemas"]["ProjectMode"];
            /** @default auto */
            language: components["schemas"]["ProjectLanguage"];
            /** Brief */
            brief?: string | null;
        };
        /**
         * ProjectLanguage
         * @enum {string}
         */
        ProjectLanguage: "auto" | "uz" | "ru" | "en";
        /** ProjectList */
        ProjectList: {
            /** Items */
            items: components["schemas"]["ProjectSummary"][];
        };
        /**
         * ProjectMode
         * @enum {string}
         */
        ProjectMode: "auto" | "assisted" | "manual";
        /** ProjectOut */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            preset: components["schemas"]["ProjectPreset"];
            /** Fps */
            fps: number;
            mode: components["schemas"]["ProjectMode"];
            status: components["schemas"]["ProjectStatus"];
            /** Asset Count */
            asset_count: number;
            /** Total Bytes */
            total_bytes: number;
            /** Progress */
            progress: number;
            active_stage: components["schemas"]["Stage"] | null;
            /** Active Stage Label */
            active_stage_label?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Target Duration Sec */
            target_duration_sec: number | null;
            language: components["schemas"]["ProjectLanguage"];
            /** Brief */
            brief: string | null;
            /** Stages */
            stages: components["schemas"]["StageOut"][];
            /** Cost Usd */
            cost_usd: number;
            /** Current Agent */
            current_agent: string | null;
        };
        /**
         * ProjectPreset
         * @enum {string}
         */
        ProjectPreset: "reels_9x16" | "youtube_16x9_1080" | "youtube_16x9_2160" | "square_1x1" | "portrait_4x5";
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "archived";
        /** ProjectSummary */
        ProjectSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            preset: components["schemas"]["ProjectPreset"];
            /** Fps */
            fps: number;
            mode: components["schemas"]["ProjectMode"];
            status: components["schemas"]["ProjectStatus"];
            /** Asset Count */
            asset_count: number;
            /** Total Bytes */
            total_bytes: number;
            /** Progress */
            progress: number;
            active_stage: components["schemas"]["Stage"] | null;
            /** Active Stage Label */
            active_stage_label?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            preset?: components["schemas"]["ProjectPreset"] | null;
            /** Fps */
            fps?: (24 | 25 | 30 | 50 | 60) | null;
            /** Target Duration Sec */
            target_duration_sec?: number | null;
            mode?: components["schemas"]["ProjectMode"] | null;
            language?: components["schemas"]["ProjectLanguage"] | null;
            /** Brief */
            brief?: string | null;
        };
        /** ReadyOut */
        ReadyOut: {
            /** Status */
            status: string;
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["ComponentCheck"];
            };
        };
        /** ShotOut */
        ShotOut: {
            /** Index */
            index: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Duration */
            duration: number;
        };
        /** SignedPart */
        SignedPart: {
            /** Number */
            number: number;
            /** Url */
            url: string;
            /**
             * Method
             * @default PUT
             */
            method: string;
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * SignedUrl
         * @description Short-lived presigned GET on the Mini App's own origin.
         */
        SignedUrl: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "upload" | "ingest" | "analysis" | "transcription" | "director" | "editor" | "color" | "audio" | "motion" | "captions" | "qa" | "render" | "delivery";
        /** StageOut */
        StageOut: {
            stage: components["schemas"]["Stage"];
            /** Label */
            label: string;
            status: components["schemas"]["StageStatus"];
            /** Progress */
            progress: number | null;
            /** Detail */
            detail: string | null;
            /**
             * Phase
             * @description Development phase in which this stage becomes operational
             */
            phase: number;
            /**
             * Available
             * @description False until the stage's phase has been built
             */
            available: boolean;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "pending" | "queued" | "running" | "done" | "failed" | "skipped" | "blocked" | "waiting_user";
        /** TelegramAuthRequest */
        TelegramAuthRequest: {
            /** Init Data */
            init_data: string;
        };
        /** UploadCreate */
        UploadCreate: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Content Type
             * @default application/octet-stream
             */
            content_type: string;
            /** Last Modified Ms */
            last_modified_ms?: number | null;
            /** Fingerprint */
            fingerprint: string;
        };
        /** UploadPartOut */
        UploadPartOut: {
            /** Number */
            number: number;
            /** Size */
            size: number;
            /** Etag */
            etag: string;
        };
        /** UploadProgressReport */
        UploadProgressReport: {
            /** Bytes Uploaded */
            bytes_uploaded: number;
            /**
             * Error
             * @description Last client-side failure (network, storage status)
             */
            error?: string | null;
        };
        /** UploadSessionOut */
        UploadSessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            status: components["schemas"]["UploadSessionStatus"];
            /** Size Bytes */
            size_bytes: number;
            /** Part Size */
            part_size: number;
            /** Part Count */
            part_count: number;
            /** Uploaded Parts */
            uploaded_parts: components["schemas"]["UploadPartOut"][];
            /** Bytes Uploaded */
            bytes_uploaded: number;
            /**
             * Resumed
             * @default false
             */
            resumed: boolean;
            asset: components["schemas"]["AssetOut"];
        };
        /**
         * UploadSessionStatus
         * @enum {string}
         */
        UploadSessionStatus: "active" | "completing" | "completed" | "aborted" | "expired" | "failed";
        /** UploadStateOut */
        UploadStateOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["UploadSessionStatus"];
            /** Bytes Reported */
            bytes_reported: number;
            /** Part Size */
            part_size: number;
            /** Part Count */
            part_count: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Telegram Id */
            telegram_id: number;
            /** Username */
            username: string | null;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Language Code */
            language_code: string | null;
            /** Photo Url */
            photo_url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoStream */
        VideoStream: {
            /** Codec */
            codec?: string | null;
            /** Profile */
            profile?: string | null;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Display Width */
            display_width: number;
            /** Display Height */
            display_height: number;
            /**
             * Rotation
             * @default 0
             */
            rotation: number;
            /** Fps */
            fps?: number | null;
            /**
             * Vfr
             * @default false
             */
            vfr: boolean;
            /** Pix Fmt */
            pix_fmt?: string | null;
            /** Bit Depth */
            bit_depth?: number | null;
            /** Chroma */
            chroma?: string | null;
            /** Bitrate */
            bitrate?: number | null;
            /** Frames */
            frames?: number | null;
            /** Color Range */
            color_range?: string | null;
            /** Color Primaries */
            color_primaries?: string | null;
            /** Color Transfer */
            color_transfer?: string | null;
            /** Color Space */
            color_space?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    telegram_login_api_v1_auth_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_presets_api_v1_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    new_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_api_v1_projects__project_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_v1_projects__project_id__assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_projects__project_id__jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reingest_asset_api_v1_assets__asset_id__reingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_api_v1_projects__project_id__uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Insufficient Storage */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_upload_api_v1_uploads__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_upload_api_v1_uploads__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_parts_api_v1_uploads__session_id__parts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartSignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartSignResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_progress_api_v1_uploads__session_id__progress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadProgressReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_api_v1_uploads__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_projects__project_id__events_get: {
        parameters: {
            query?: {
                before_id?: number | null;
                after_id?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_projects__project_id__events_stream_get: {
        parameters: {
            query?: {
                after_id?: number;
            };
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
